### ISSUE TITLE
Export counts method

### ISSUE THREAD

**Issue by lazappi** [drisso/SingleCellExperiment#1]
The counts accessor method doesn't seem to be exported. The other accessors (cpm, tpm etc.) are in NAMESPACE but not counts. If it could be added that would be great (unless there is some reason not to that I'm not aware of).

Thanks

**Comment by LTLA** [comment]
`counts` comes from _BiocGenerics_, which should be visible after `library(SingleCellExperiment)` as _SummarizedExperiment_ is `Depend`ed on (which in turn `Depend`s on _BiocGenerics_). I guess we could add `counts` as an exported method in _SingleCellExperiment_, but I don't know the etiquette for re-exporting an already-exported method from another package.

**Comment by lazappi** [comment]
I looked in _SingleCellExperiment_ and _SummarizedExperiment_ but I didn't think about _BiocGenerics_. I can access it from there so there's probably no need to export it again. It's probably only an issue when developing packages, when doing analysis the package will be loaded so it should be fine.

Thanks!
