### ISSUE TITLE
Make subset() behave more expected

### ISSUE THREAD

**Issue by flying-sheep** [drisso/SingleCellExperiment#17]
`subset` usually evaluates its arguments in a `with` context.

furthermore, i’d expect a left out i or j to mean “all rows” / “all columns”

i’d like to see this working:

```r
sce <- SingleCellExperiment(..., colData = DataFrame(Cluster = ...))
sce_subset <- subset(sce, , Cluster %in% c('foo', 'bar'))
```

**Comment by LTLA** [comment]
Or a much simpler solution - delete the `subset` method entirely from this package, and rely on the base method in _SummarizedExperiment_. See 31d42d734f084c7f7e9f40850cf86eb314a6f121 for details.

```r
library(SingleCellExperiment)
example(SingleCellExperiment) # create sce
sce$WHEE <- sample(LETTERS, ncol(sce), replace=TRUE)
out <- subset(sce, , WHEE=="A")
out$WHEE
## [1] "A" "A" "A" "A" "A"
```

**Comment by flying-sheep** [comment]
well, that works too :laughing:
