### ISSUE TITLE
Lack of withNames argument to counts(), tpm(), etc.

### ISSUE THREAD

**Issue by PeteHaitch** [drisso/SingleCellExperiment#19]
Was this a deliberate design choice? It means, for example, that these methods called on a HDF5-backed *SingleCellExperiment* will always return a *DelayedArray* rather than a *HDF5Array*. This can cause surprises to the user (not the fault of **SingleCellExperiment**, but just something I've experienced). Adding `withDimnames = TRUE` as the default would preserve current behaviour but allow users/developers to override as needed.

**Comment by LTLA** [comment]
No, not a deliberate design choice. Make a PR if you wish.

**Comment by PeteHaitch** [comment]
Cheers, will do
