### ISSUE TITLE
Test fails in Travis but not on my local machine

### ISSUE THREAD

**Issue by drisso** [drisso/SingleCellExperiment#21]
See here:
https://travis-ci.org/drisso/SingleCellExperiment/jobs/397237538#L1574

One of the tests at https://github.com/drisso/SingleCellExperiment/blob/master/tests/testthat/test-lem-combine.R#L52 failed.

On my Mac all tests are OK.

**Comment by LTLA** [comment]
Smells like something to do with the recent updates to `S4Vectors`, which now allows for duplicated sample names. You can see that there is no longer the disambiguating "1" added to the end of the name.

**Comment by drisso** [comment]
It apparently just fixed itself 🤷‍♂️ 
https://travis-ci.org/drisso/SingleCellExperiment/jobs/405009228
