### ISSUE TITLE
Extracting counts data as dataframe

### ISSUE THREAD

**Issue by DrLucyMac** [drisso/SingleCellExperiment#22]
Hi there, 

I have a SCE object on which I am applying various clustering algorithms - some of which, require the input of counts data as a dataframe. Can you please help me understand how I would go about extracting this information from the SCE object, getting counts(object) into a data frame? 

Cheers!

**Comment by LTLA** [comment]
```r
data.frame(counts(sce))
```

**Comment by DrLucyMac** [comment]
I have tried that but just keep getting.. 

```
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ‘structure("dgCMatrix", package = "Matrix")’ to a data.frame
```

**Comment by LTLA** [comment]
Well, that's because you have a sparse matrix. It's got nothing to do with _SingleCellExperiment_.

I would normally tell you to ask for help in a general R forum like R-help, but it's just easier to tell you:

```r
data.frame(as.matrix(counts(sce)))
```

Densify-ing a sparse matrix will increase memory usage, so be careful.

**Comment by DrLucyMac** [comment]
Thanks for your help.

Lucy
