### ISSUE TITLE
weights accessor

### ISSUE THREAD

**Issue by dcellwanger** [drisso/SingleCellExperiment#23]
Hello @drisso and @LTLA,

One of your recent updates of the `SingleCellExperiment` package causes a namespace issue with the `weights` accessor when building a dependent package (e.g., https://travis-ci.com/dcellwanger/CellTrails/jobs/136908584): "replacing previous import 'SingleCellExperiment::weights' by 'stats::weights' when loading ...'

Any idea on how to resolve that?

Thanks!

**Comment by LTLA** [comment]
In your `NAMESPACE`, you `import(stats)`. You should probably be more selective to avoid namespace collisions, especially as it seems that you don't use `stats::weights` anywhere in your package.

**Comment by dcellwanger** [comment]
Thanks for the quick response and the hint - selectively importing functions from `stats` solved the issue;`import(methods, except=weights)` should also work. I am wondering how to solve this issue in the case a dependent package actually uses `stats::weights`, as functions of `stats` [need to be imported](http://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2015/06/29#n2015-06-29) to pass the CRAN check.

**Comment by LTLA** [comment]
Just import selectively (excluding `weights`) and then call `stats::weights` where required.
