### ISSUE TITLE
don’t use “Depends”

### ISSUE THREAD

**Issue by flying-sheep** [drisso/SingleCellExperiment#25]
SummarizedExperiment pulls in a lot stuff that populates my namespace and overrides symbols.

I’d like to only have methods for SingleCell/SummarizedExperiment, and AFAIK they’re available automatically for S4 classes anyway.

**Comment by LTLA** [comment]
This behaviour is unlikely to change. The _SingleCellExperiment_ package is intended to be user-facing, so methods like `rowData`, `colData`, etc. should be exposed to the global namespace, in much the same way that the core Bioconductor S4 methods (e.g., `metadata`, `mcols`) from _S4Vectors_ and _BiocGenerics_ are indirectly exposed by _SummarizedExperiment_ via the `Depends` on _GenomicRanges_.

I assume that you're referring to overriding of internal function names in your package namespace. In such cases, a more Bioconductor-friendly solution would be to change your function names or write them as methods for the existing generics. If you're referring to overriding of exported function names, then you have a bigger problem as you will clash with _SummarizedExperiment_ in the global namespace - causing problems for anyone who loads your package and SE in the same session.

**Comment by flying-sheep** [comment]
My package? No, I mean this:

```r
> library(tidyverse)
-- Attaching packages --------------------------------------- tidyverse 1.2.1 --
v ggplot2 3.0.0     v purrr   0.2.4
v tibble  1.4.2     v dplyr   0.7.6
v tidyr   0.8.1     v stringr 1.3.1
v readr   1.1.1     v forcats 0.3.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
> library(SingleCellExperiment)
Lade nötiges Paket: SummarizedExperiment
Lade nötiges Paket: GenomicRanges
Lade nötiges Paket: stats4
Lade nötiges Paket: BiocGenerics
Lade nötiges Paket: parallel

Attache Paket: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap, parApply, parCapply, parLapply, parLapplyLB, parRapply,
    parSapply, parSapplyLB

The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames, colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep, grepl,
    intersect, is.unsorted, lapply, lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank, rbind,
    Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort, table, tapply, union, unique, unsplit, which, which.max, which.min

Lade nötiges Paket: S4Vectors

Attache Paket: ‘S4Vectors’

The following objects are masked from ‘package:dplyr’:

    first, rename

The following object is masked from ‘package:tidyr’:

    expand

The following object is masked from ‘package:base’:

    expand.grid

Lade nötiges Paket: IRanges

Attache Paket: ‘IRanges’

The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice

The following object is masked from ‘package:purrr’:

    reduce

The following object is masked from ‘package:destiny’:

    distance

Lade nötiges Paket: GenomeInfoDb
Lade nötiges Paket: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with 'browseVignettes()'. To cite Bioconductor, see 'citation("Biobase")', and for packages
    'citation("pkgname")'.

Lade nötiges Paket: DelayedArray
Lade nötiges Paket: matrixStats

Attache Paket: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians

The following object is masked from ‘package:dplyr’:

    count


Attache Paket: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following object is masked from ‘package:base’:

    apply
```

**Comment by LTLA** [comment]
I don't think any of these things have to do with _SingleCellExperiment_. For example, a lot of masking occurs from _BiocGenerics_ symbols. Take it up with the relevant upstream packages.

**Comment by flying-sheep** [comment]
excactly that’s my problem: SingleCellExperiment uses “Depends” for “SummarizedExperiment”, which makes “SummarizedExperiment” pull in its “Depends” and so on.

none of those packages should use “Depends”, but SCE starts the chain for me.

SCE could simply use `importFrom(SummarizedExperiment, rowData)` + `export(rowData)` instead of forcing the attaching of the whole shebang.

**Comment by LTLA** [comment]
I beg to differ. "Writing R extensions" states that

> Field ‘Depends’ should nowadays be used rarely, only for packages which are intended to be put on the search path to make their facilities available to the end user (and not to the package itself): for example it makes sense that a user of package latticeExtra would want the functions of package lattice made available.

And I **do** want to make the _SummarizedExperiment_ facilities available to the end user. So, yes, I will be using `Depends` - otherwise everyone would have to do:

```r
library(SingleCellExperiment)
library(SummarizedExperiment)
```

... any time they wanted to create or manipulate an SCE, which would be much more inconvenient.

I will note that most of the masking doesn't matter, as the functions do the same thing, e.g., `base::colnames` and `BiocGenerics::colnames`. The rest you can discuss with the relevant package maintainers.

**Comment by flying-sheep** [comment]
do you? the only things SummarizedExperiment exports are those non-generic functions

```r
export(
    Assays,
    .DollarNames.SummarizedExperiment,
    .DollarNames.RangedSummarizedExperiment,
    makeSummarizedExperimentFromExpressionSet,
    makeSummarizedExperimentFromDataFrame,
    makeSummarizedExperimentFromLoom,
    naiveRangeMapper, probeRangeMapper, geneRangeMapper,
    readKallisto, readKallistoBootstrap, KALLISTO_ASSAYS
)
```

of which i don’t really want anything when dealing with SCEs, and those generics:

```r
export(
    SummarizedExperiment,
    "rowRanges<-",
    rowData, "rowData<-",
    colData, "colData<-",
    assayNames, "assayNames<-",
    assays, "assays<-",
    assay, "assay<-"
)
```

which are limited enough that you could reexport them.

S4 methods for generics defined elsewhere are available automatically, no need to attach a package for that.

**Comment by LTLA** [comment]
There's a lot of stuff in _S4Vectors_ and _BiocGenerics_ that need to be considered as well, as these apply to the base classes from which _SummarizedExperiment_ is derived. For example, `S4Vectors::metadata`, `BiocGenerics::rownames`, `BiocGenerics::colnames`, to name a few - also `BiocGenerics::cbind` and `rbind`. I'm sure there's more methods that I don't commonly use, but I don't want to have to manually update my export list every time new functionality is added in SE or other core packages.

If I were to re-export everything to provide full SE support - not just for you, but for other people who might be expecting it - you'd eventually get the same masking problem anyway. And if you were to ever load SE itself or _GenomicRanges_, then you'd get the same masking problem. So any solution - if this is indeed a problem - cannot occur at the level of _SingleCellExperiment_.

**Comment by flying-sheep** [comment]
OK, you convinced me. You also convinced me that SE, S4Vectors and the whole kitchen sink is hopelessly overengineered.

S4Vectors being incompatible with the tidyverse (DataFrame) is pretty bad form these days, and it’s sad that the bio world coded itself into this bubble.

of course I understand that this is the route you had to follow with the whole genomicranges stuff and for the sake of compatibility (instead of creating YET ANOTHER incompatible class – stupid SeuratObject and whatever else there is)

**Comment by LTLA** [comment]
I don't use or like the tidyverse, so I don't have an opinion either way. If you want, you can raise an issue on _S4Vectors_ or _BiocGenerics_; I'm sure that @lawremi or @hpages could provide you with more insights into the design decisions related to the Bioconductor core infrastructure.

**Comment by hpages** [comment]
The Bioconductor core infrastructure (including DataFrame) that is implemented in packages _S4Vectors_, _IRanges_, _GenomicRanges_, _SummarizedExperiment_, etc... has been around for years and predates the tidyverse. Bioconductor and the tidyverse do share many symbols these days but that is just a natural consequence of their growth.

Note that, generally speaking, a symbol masking another symbol does not necessarily mean there is a conflict. For example the masking of _base_, _stats_, or _parallel_ symbols by _BiocGenerics_ symbols are not conflicts (original semantics is preserved). Actually most of the time masking does not mean conflict. FWIW @hadley is about to release _conflicted_, a package that will help deal with masking/conflicts. A nice feature of conflicted is that it will be able to distinguish between masking that does not conflict and masking that is potentially a conflict. If the latter, it will let the user know about it and ask him/her to disambiguate.

For more information, see Hadley's [recent post](https://stat.ethz.ch/pipermail/r-devel/2018-August/076644.html) on R-devel, and also [this](https://github.com/r-lib/conflicted/issues/8) discussion about conflicting vs not-conflicting.

**Comment by flying-sheep** [comment]
ah, that’s a good development! thank you for the info.

still, I’ve never seen a DataFrame in the wild until using SE/SCE and don’t understand why they had to be created…

**Comment by lawremi** [comment]
DataFrames extend the idea of data.frame to abstract vectors, so for example, we can have an Rle object, a GRanges, or any other vector-like object as a column. They also support annotations on their columns, like the old AnnotatedDataFrame from Biobase.

**Comment by flying-sheep** [comment]
I don’t want to drag out this thread even more. I understand why people thought they should do it (because it was cleaner) but it could have been solved in a more practical and compatible way (subclass data.frame, override all the “primitive” methods like `[`, `[[`, `$`, `names`, …)

**Comment by lawremi** [comment]
In practice that would not work so well, because the alternative column types wouldn't be supported by legacy code. At least now, anything that calls `as.data.frame()` gets something conventional. Using a separate representation creates a barrier between abstract and legacy code that helps ensure robustness.
