### ISSUE TITLE
Is there any R package supporting DotPlot() for SingleCellExperiment object?

### ISSUE THREAD

**Issue by genecell** [drisso/SingleCellExperiment#28]
Hi,

I am a fan of SingleCellExperiment!
I have been looking for existing R packages which support drawing **DotPlot** for SingleCellExperiment object, but have not found yet.
DotPlot is suitable for users to show the expression patterns of marker genes across cell types or user-assigned clusters. DotPlot is well supported in Seurat: [DotPlot()](https://satijalab.org/seurat/v3.0/visualization_vignette.html).
In addition, I checked SC3, scater and scran, and found no DotPlot() there.
If you know any R package supporting DotPlot() for SingleCellExperiment object, please let me know. Thanks in advance!

Best regards,
BP

**Comment by LTLA** [comment]
Not to my knowledge. 

Personally, I've always been very wary of any visualization that uses area to encode information. Humans are notoriously bad at comparing areas, and in this case, I've felt that two plots are better than one. (And no, maximizing the "density of information per pixel" is not the aim of the game here.)

So, I don't feel any particular desire to write up a dot-plot function. But if you like this visualization enough that you want to write one and put it in a package somewhere, I would suggest making a PR in the _scater_ repository (https://github.com/davismcc/scater), where SCE-based visualization methods already reside.

**Comment by genecell** [comment]
Hi @LTLA,

Thank you for your suggestion.
I agree.

Best regards,
BP

**Comment by LTLA** [comment]
I'll close this, then; open a PR at _scater_'s repository if you want to follow up.
