### ISSUE TITLE
Joining `sce` objects (extension to `cbind`)

### ISSUE THREAD

**Issue by robertamezquita** [drisso/SingleCellExperiment#29]
A common issue that comes up that isn't super friendly to deal with (esp for beginners) is when it comes to `cbind(sce1, sce2)` and they have differing `mcols` (e.g., `rowData`) that prevents them being joined. 

Example:

```r
library(TENxPBMCData)
pbmc3k <- TENxPBMCData('pbmc3k')
pbmc4k <- TENxPBMCData('pbmc4k')
cbind(pbmc3k, pbmc4k)

## Error in FUN(X[[i]], ...) : 
##  column(s) 'ENSEMBL_ID' in ‘mcols’ are duplicated and the data do not match
```

Typically, the solution I use is to harmonize the rows first, and then set `rowData(sce1) <- rowData(sce2) <- NULL` so I can `cbind` them, re-adding the `rowData` after that.

To circumvent this, I could see there being a join method (a la dplyr verbage), e.g. `inner_join` only using common rownames (or `by` some col in `rowData`).

**Comment by LTLA** [comment]
Sounds like a problem for https://github.com/sa-lee/plyexperiment.
