### ISSUE TITLE
loom support

### ISSUE THREAD

**Issue by flying-sheep** [drisso/SingleCellExperiment#6]
we probably want this: [loom](http://loompy.org/)

**Comment by LTLA** [comment]
I was thinking of this too. The best way to do it would be with a _loomR_ package or something, that reads a `loom` file and produces a `SingleCellExperiment` instance (or writes the object to a `loom` file). I wouldn't put the relevant functions into the _SingleCellExperiment_ package itself, though.

The `loom` format seems to be HDF5-backed, so it may in fact be simple to slap it into a `HDF5Matrix`, assuming that the relevant matrices are stored as HDF5 datasets within the file. It would then be an "easy" matter of pulling out annotation via _rhdf5_ to construct the final _SingleCellExperiment_ object.

**Comment by LTLA** [comment]
See https://github.com/linnarsson-lab/loompy/issues/6.
