### ISSUE TITLE
SingleCellExperiement and Seurat V5

### ISSUE THREAD

**Issue by ondina-draia** [drisso/SingleCellExperiment#77]
Hello,

I encounter a problem with latest version of the Seurat object (V5 Assays), when I try to convert in SingleCellExperiment format, I get the following error: 

```
Error in `GetAssayData()`:
! GetAssayData doesn't work for multiple layers in v5 assay
```

I tried to find a workaround to this trouble by manually creating the SingleCellExperiment object manually: 

```
# Convert to V3/4 assay
obj$P30.N <- NormalizeData(obj$P30.N, assay = "RNA")
obj$P30.N[["RNA3"]] <- as(object = obj$P30.N[["RNA"]], Class = "Assay")

# Raw data stored in RNA3 as counts
counts <- GetAssayData(obj$P30.N, assay = "RNA3", slot = "counts")

# Extract normalized counts
#normalized_counts <- GetAssayData(obj$P30.N, assay = "RNA3", slot = "data")

# MetaData
meta_data <- obj$P30.N@meta.data

# Create SingleCellExperiment object
P30.N.sce <- SingleCellExperiment(
  assays = list(counts = counts, logcounts = normalized_counts),
  colData = meta_data
)

# Extract PCA data
pca_coords <- Embeddings(obj$P30.N, reduction = "pca")

# Ajouter les coordonnées PCA à l'objet SingleCellExperiment
reducedDim(P30.N.sce, "PCA") <- pca_coords

# If thereés UMAP embeddings, extract them:
if ("umap" %in% names(obj$P30.N@reductions)) {
  umap_coords <- Embeddings(obj$P30.N, reduction = "umap")
  reducedDim(P30.N.sce, "UMAP") <- umap_coords
}

```

It seems to work but some of the results I get are looking odd. 

What should I do?

**Comment by LTLA** [comment]
I'm afraid I can't help much, I haven't looked at **Seurat** in a very long time.

**Comment by drisso** [comment]
I would ask this question to the Seurat's authors as it seems that the possible issue is with the extraction of the right components of the Seurat object. 

Have you tried Seurat's `as.SingleCellExperiment` function? I'm not sure about the latest version, but it used to do a decent job at converting Suerat's object into a SingleCellExperiment

**Comment by ondina-draia** [comment]
It's with as.SingleCellExperiment() that I get the error. I guess I'll continue searching for a solution.

**Comment by drisso** [comment]
I see. Sorry, I misunderstood the first part of your question. I would perhaps open an issue in the Seurat repo, reporting the error since that function belongs to Seurat.

**Comment by ondina-draia** [comment]
No worries, I'll submit an issue myself. I should have started there. Thank you anyway!
