### ISSUE TITLE
Saving a SingleCellExperiment  containing a dgCMatrix with "saveHDF5SummarizedExperiment"

### ISSUE THREAD

**Issue by chriad** [drisso/SingleCellExperiment#9]
Hi,

I wonder if it would be possible to save a SingleCellExperiment (which is a SummarizedExperiment) with a sparse matrices of type "dgCMatrix" in the assays slot to a HDF5-based SummarizedExperiment object?

Now I just save it as a R object with saveRDS. Maybe this is also sufficient, but since the "saveHDF5SummarizedExperiment" function exists I thought it would be nice if one could also use it to save a sparse format.

```
> saveHDF5SummarizedExperiment(se_test)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'type' for signature '"dgCMatrix"'
```

**Comment by LTLA** [comment]
As far as I know, the `saveDF5SummarizedExperiment` function will use the `writeHDF5Array` function from the _HDF5Array_ package to save matrices. Even if the function had defined behaviour for `dgCMatrix` objects (which it doesn't seem to have), it would simply coerce the matrix into a `HDF5Matrix` format, i.e., a dense matrix stored on disk in a HDF5 file. At that point, it would no longer be a sparse matrix.

Densifying the matrix is necessary to take advantage of the HDF5 library's ability to rapidly access data from different parts of the matrix. If you want to preserve sparsity, you're better off saving it as an RDS file, which does the same job for data access in R. In any case, this is a question better suited to the BioC-devel list (_HDF5Array_ and _SummarizedExperiment_ are both Bioconductor packages; this question hasn't much to do with _SingleCellExperiment_), so post there if you want more information.
